#!/bin/csh

# renice 10 -u arunp

setenv CDS_AUTO_64BIT ALL
setenv CDS_Netlisting_Mode Analog
setenv MGC_HOME /opt/mentor/calibre/2019.3_15.11
setenv QRC_HOME /u/cadence/EXT/19.13
setenv PVS_HOME /opt/cadence/PVS/19.13
setenv ASSURAHOME /opt/cadence/ASSURA/618-4.16.102
set path = ($path $ASSURAHOME/tools/bin)
 

# use IC_CDB   #Original way of running icfb
use IC
use calibre
use EXT
use PVS
use ASSURA
use INCISIVE
use SPECTRE
#use MMSIM
use SIGRITY
use hspice

# icfb   &
#virtuoso &


